version: "3.9"
services:
  fetcher:
    build: .
    volumes:
      - ./data:/app/data

  influxdb:
    image: influxdb:2.1.1
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mydb
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=user:password

  grafana:
    image: grafana/grafana:8.3.6
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

  web:
      build: ./webapp
      ports:
        - "5000:5000"
      depends_on:
        - influxdb

volumes:
  influxdb-data:
  grafana-data: